### ISSUE TITLE
[BUG] Jetson Nano 4GB - depthai_demo.py error - qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by kirahman2** [luxonis/depthai#1089]
**Describe the bug**
Hey all, I'm hitting a wall! I've been troubleshooting this issue for 20-25 hours or so. When I install depthai using the instructions linked [here](https://docs.luxonis.com/projects/api/en/latest/install/#jetson) for my Nvidia Jetson Nano 4GB and run the following code 

`python3 depthai_demo.py` 

I get the error / output below 

```
khalid@khalidjetson:~/Luxonis/depthai$ python3 depthai_demo.py
Using depthai module from:  /home/khalid/.local/lib/python3.10/site-packages/depthai.cpython-310-aarch64-linux-gnu.so
Depthai version installed:  2.21.2.0
Setting up demo...
Available devices:
[0] 18443010F1AA721200 [X_LINK_UNBOOTED]
USB Connection speed: UsbSpeed.SUPER
Downloading /home/khalid/.cache/blobconverter/mobilenet-ssd_openvino_2021.4_6shave.blob...
[==================================================]
Done
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/khalid/.local/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

I've also tried installing depthai manually using the doc linked [here](https://docs.luxonis.com/en/latest/pages/tutorials/manual_installation/#manual-depthai-installation) and I still get the same above error.  

**Minimal Reproducible Example**

Append the MRE to the bug report, [instructions here]
(https://docs.luxonis.com/en/latest/pages/support/#creating-minimal-reproducible-example)
I'm SSHing from my macos system to my Jetson Nano 4GB kit. Then I'm following the Jetson Nano Luxinos guide linked [here](https://docs.luxonis.com/projects/api/en/latest/install/#jetson). I have JetPack 4.6.1 installed on my Jetson Nano. This means it comes with Python 3.6.1. I've updated to python 3.10.11 successfully, so that is not an issue. 
```
khalid@khalidjetson:~/Luxonis/depthai$ python3 --version
Python 3.10.11
```

**Expected behavior**
I'm expecting the depthai_demo.py script to run successfully without any errors. 

**Pipeline Graph**

Please also provide a screenshot of your pipeline using the [DepthAI Pipeline Graph](https://github.com/geaxgx/depthai_pipeline_graph).

I attempted to use `pipeline_graph` . When I ran this, I received the error mentioned in the guide. 

```
khalid@khalidjetson:~/Luxonis/depthai$ pipeline_graph "python3 depthai_demo.py"
Traceback (most recent call last):
  File "/home/khalid/.local/bin/pipeline_graph", line 5, in <module>
    from depthai_pipeline_graph.pipeline_graph import main
  File "/home/khalid/.local/lib/python3.10/site-packages/depthai_pipeline_graph/pipeline_graph.py", line 7, in <module>
    from Qt import QtWidgets, QtCore
  File "/home/khalid/.local/lib/python3.10/site-packages/Qt.py", line 1938, in <module>
    _install()
  File "/home/khalid/.local/lib/python3.10/site-packages/Qt.py", line 1886, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.
```

Then I attempted to run `pip install PySide2` per the guides recommendation, but I received the following error
```
khalid@khalidjetson:~/Luxonis/depthai$ pip install PySide2
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)
ERROR: No matching distribution found for PySide2
```

**Attach system log**
 - Provide output of [log_system_information.py](https://github.com/luxonis/depthai/blob/main/log_system_information.py)
```
khalid@khalidjetson:~/Luxonis/depthai$ python3 log_system_information.py 
{
    "architecture": "64bit ELF",
    "machine": "aarch64",
    "platform": "Linux-4.9.337-tegra-aarch64-with-glibc2.27",
    "processor": "aarch64",
    "python_build": "main Jul 25 2023 19:48:07",
    "python_compiler": "GCC 7.5.0",
    "python_implementation": "CPython",
    "python_version": "3.10.11",
    "release": "4.9.337-tegra",
    "system": "Linux",
    "version": "#1 SMP PREEMPT Thu Jun 8 21:19:14 PDT 2023",
    "win32_ver": "",
    "packages": [
        "blobconverter==1.4.2",
        "boto3==1.28.11",
        "botocore==1.31.11",
        "certifi==2023.7.22",
        "charset-normalizer==2.0.12",
        "depthai==2.21.2.0",
        "depthai-pipeline-graph @ git+https://github.com/luxonis/depthai_pipeline_graph.git@848a147009ffca578a85910ed298ab4430c67727",
        "depthai-sdk==1.9.4",
        "distinctipy==1.2.2",
        "ffmpy3==0.2.4",
        "idna==3.4",
        "jmespath==1.0.1",
        "lz4==4.3.2",
        "marshmallow==3.17.0",
        "mcap==1.1.0",
        "mcap-ros1-support==0.0.8",
        "numpy==1.25.1",
        "opencv-contrib-python==4.5.5.62",
        "packaging==23.1",
        "pip==23.2.1",
        "python-dateutil==2.8.2",
        "pytube==15.0.0",
        "PyTurboJPEG==1.6.4",
        "pyusb==1.2.1",
        "PyYAML==6.0.1",
        "Qt.py==1.3.8",
        "requests==2.26.0",
        "rosbags==0.9.11",
        "ruamel.yaml==0.17.32",
        "ruamel.yaml.clib==0.2.7",
        "s3transfer==0.6.1",
        "scipy==1.11.1",
        "sentry-sdk==1.5.1",
        "setuptools==65.5.0",
        "six==1.16.0",
        "types-PySide2==5.15.2.1.5",
        "urllib3==1.26.16",
        "xmltodict==0.13.0",
        "zstandard==0.21.0"
    ],
    "usb": [
        {
            "port": 1,
            "vendor_id": "0x0bda",
            "product_id": "0x0411",
            "speed": "Super"
        },
        {
            "port": 0,
            "vendor_id": "0x1d6b",
            "product_id": "0x0003",
            "speed": "Super"
        },
        {
            "port": 4,
            "vendor_id": "0x03e7",
            "product_id": "0x2485",
            "speed": "High"
        },
        {
            "port": 2,
            "vendor_id": "0x0bda",
            "product_id": "0x5411",
            "speed": "High"
        },
        {
            "port": 0,
            "vendor_id": "0x1d6b",
            "product_id": "0x0002",
            "speed": "High"
        }
    ],
    "uname": [
        "Linux khalidjetson 4.9.337-tegra #1 SMP PREEMPT Thu Jun 8 21:19:14 PDT 2023 aarch64 aarch64"
    ]
}
System info gathered successfully - saved as "log_system_information.json"
```

**Additional context**
I've tried many many different installation attempts, but each one seems to have the same exact error / outcome that I mentioned at the top of this ticket. Hoping someone can help!

**Comment by Erol444** [comment]
Hi @kirahman2 ,
Looks like there's a problem with QT. I'd suggest using Depthai-Viewer instead, which will soon replace depthai_demo anyways: https://github.com/luxonis/depthai-viewer

**Comment by Erol444** [comment]
Looks like we haven't yet built wheels for arms.. cc @zrezke

**Comment by zrezke** [comment]
> Looks like we haven't yet built wheels for arms.. cc @zrezke 

Yea, not available yet. I'll investigate later

**Comment by zrezke** [comment]
Hi @kirahman2 ,
I think the best way for you to get up and running using depthai-viewer on Jetson is by building from source. This is because of Linux4Tegra OS which is based on ubuntu 18.04 which isn't supported by depthai-viewer (or rerun), and we also currently don't provide any ARM wheels. Here is a relevant issue [depthai viewer on ubuntu 18.04](https://github.com/luxonis/depthai-viewer/issues/25).

### Building from source
- Install the Rust toolchain: https://rustup.rs/
- `git clone git@github.com:luxonis/depthai-viewer.git && cd depthai-viewer`
- Run `./scripts/setup_dev.sh`.
- Make sure `cargo --version` prints 1.70 once you are done

```sh
python3.8 -m pip install rerun_py/
```

**Comment by zrezke** [comment]
Hey @kirahman2 ,
Not sure on this, maybe you can try with the workaround mentioned [here](https://github.com/PyO3/pyo3/issues/1568)

**Comment by zrezke** [comment]
@kirahman2 Nice, I'm happy you got it installed. The examples are not guaranteed to work. They are the examples from [rerun](https://github.com/rerun-io/rerun), we just have them in there because depthai-viewer was forked from rerun. Could you try running the depthai-viewer like this:
```sh
depthai-viewer
# If this fails use:
python3 -m depthai_viewer
```
, and then try to connect to your device via the UI on the right side.

**Comment by zrezke** [comment]
#### Some suggestions
Try installing these:
```sh
sudo apt-get install -y libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev
```
If this doesn't resolve the issue, you could try using the opengl WGPU backend instead of vulkan, like this:
```sh
WGPU_BACKEND=gl depthai-viewer
```

Otherwise please post the output of this command (needs to be installed first via apt):
```sh
inxi -Gxx | grep compositor
```

Since you switched to Ubuntu 20.04 you may have to build nvidia's vulkan loader on device: https://developer.nvidia.com/embedded/vulkan

**Comment by zrezke** [comment]
Hey @kirahman2 - Hmm, I assume you are still ssh-ing into your jetson nano - It's quite possible that the issue is caused by using a terminal only session 
```sh
jetson@nano:~/Vulkan-Loader$ inxi -Gxx | grep compositor
  compositor: gnome-shell tty: 80x24
  ```
  I wonder what the output of  `inxi -Gxx | grep compositor` command is when you hook up a KB and display port / hdmi to it and run the command in the ubuntu gui session.  It's quite possible that the viewer will also work then. (This is all assuming you are currently using ssh).
  I also noticed in your [previous comment](https://github.com/luxonis/depthai/issues/1089#issuecomment-1664487271), that the `DISPLAY` environment variable is not set. If you are using X11 this should be set, on wayland the coresponding variable is `WAYLAND_DISPLAY`. 
  ```
  jetson@nano:~/Vulkan-Loader$ vulkaninfo
...
'DISPLAY' environment variable not set... skipping surface info
==========
VULKANINFO
...
```

But yea - I would first try to get an ubuntu gui running and then try to run depthai-viewer again.

**Comment by zrezke** [comment]
If it turns out to work in the ubuntu graphical session, you can probably run depthai-viewer via ssh,[ using X11 forwarding](https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely), [or a similar thing for wayland](https://gitlab.freedesktop.org/mstoeckl/waypipe)

**Comment by zrezke** [comment]
Hey @kirahman2 - I am not to sure on this. One thing you could try to do that may help with investigating this issue is running depthai-viewer with RUST_LOG=debug and RUST_BACKTRACE=1 set. We may find something interesting in those logs...  Try using those env variables and do two runs - one with WGPU_BACKEND=gl and one with WGPU_BACKEND=vulcan. Since this is a wgpu issue you may also try to run some [wgpu examples](https://github.com/gfx-rs/wgpu/tree/trunk/examples) and see if those work. If they don't they are most likely better documented so it will be easier to debug them. Just pasting this here aswell - seems similar https://github.com/gfx-rs/wgpu/issues/1787

**Comment by zrezke** [comment]
Yea, should be closed here, I'll open an issue on depthai-viewer and link this one [there](https://github.com/luxonis/depthai-viewer/issues/33).

**Comment by zrezke** [comment]
Yea, should be closed here, I'll open an issue on depthai-viewer and link this one https://github.com/luxonis/depthai-viewer/issues/33.

**Comment by AnshumanFauzdar** [comment]
> Hi @kirahman2 , I think the best way for you to get up and running using depthai-viewer on Jetson is by building from source. This is because of Linux4Tegra OS which is based on ubuntu 18.04 which isn't supported by depthai-viewer (or rerun), and we also currently don't provide any ARM wheels. Here is a relevant issue [depthai viewer on ubuntu 18.04](https://github.com/luxonis/depthai-viewer/issues/25).
> 
> ### Building from source
> * Install the Rust toolchain: https://rustup.rs/
> * `git clone git@github.com:luxonis/depthai-viewer.git && cd depthai-viewer`
> * Run `./scripts/setup_dev.sh`.
> * Make sure `cargo --version` prints 1.70 once you are done
> 
> ```shell
> python3.10 -m pip install rerun_py/
> ```

Is there any way to compile whl and share here for future reference?

**Comment by zrezke** [comment]
Hi @AnshumanFauzdar! At the moment the viewer doesn't work with the Jetson nano, so providing wheels wouldn't be of much use (look at the above reported errors with WebGPU). It has to be debugged, but it's low priority right now...

**Comment by roboticsmick** [comment]
Can this be added to the guide?

**Comment by zrezke** [comment]
Hi @roboticsmick , yea thats a good idea.
@jakaskerl could you add a mention that it doesnt work on jetson nano in the [guide](https://docs.luxonis.com/en/latest/pages/tutorials/first_steps/#first-steps-with-depthai)

**Comment by mahmad096** [comment]
> I was able to launch depthai successfully. When I tried launching depthai-viewer I received an error. I'm happy with this result. I know that depthai-viewer is in beta at the moment so that's probably expected behavior for now.


By DepthAI you mean depthai_demo.py file, with the GUI?

**Comment by ammar3010** [comment]
After running ./scripts/setup_dev.sh I am getting this error:

```
dpkg: unrecoverable fatal error, aborting:
 loading files list file for package 'libksba8:arm64': cannot open /var/lib/dpkg/info/libksba8:arm64.list (Structure needs cleaning)
E: Sub-process /usr/bin/dpkg returned an error code (2)
```
