### ISSUE TITLE
Interactive Face Recognition Demo

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#334]
### Start with the `why`:

In many applications (including interactive robotics) it is beneficial for the system to be able to know which person it is interacting with (even if it doesn't know this person by personally-identifiable information like a name).  And the flow of face detection, to then facial landmark detection, to then re-identification is a great demonstrator/reference app for other such similar applications (including recognizing specific/unique vehicles, for example) and more broadly how to build such flows with the Gen2 Pipeline Builder https://github.com/luxonis/depthai/issues/136.  So it serves as a good reference from which other similar flows can be built (such as, this car drove by X number of times, or that car keeps parking illegally).

### Move to the `how`:

Intel provides an example of this flow using OpenVINO on a computer [here](https://docs.openvinotoolkit.org/2020.1/_demos_python_demos_face_recognition_demo_README.html).  We initially built a hard-coded version of this (video [here](https://docs.openvinotoolkit.org/2020.1/_demos_python_demos_face_recognition_demo_README.html) in architecting the Gen2 Pipeline Builder https://github.com/luxonis/depthai/issues/136, to guide what nodes/systems would be needed.

Now that the Gen2 Pipeline Builder is nearing formal release, it is likely already possible to implement the whole flow using this Gen2 API, so that it can be modularly changed/added-to/reworked for other applications.

### Move to the `what`:

Implement the Interactive Face Recognition Demo in the Gen2 Pipeline Builder architecture.

**Comment by dhruvsheth-ai** [comment]
Might be a bit late to add to this. Since the Gen2 API is yet under active development, the model `facial-landmarks-35-adas-0002` can be integrated, to provide a base framework for many Advanced Driver Assistance Systems like the once you mentined above, and one of the others mentioned in pyimagesearch, an application of Eye Aspect Ratio. can be built on top of 35 Facial landmarks OpenVINO Model. 

![image](https://user-images.githubusercontent.com/67831664/110762754-25184a00-8277-11eb-92c3-f0aea47161e3.png)
 
There are a few scripts built on top of the existing 35 facial landmark model to implement that application, using Myriad X, there NCS2 but could be changed to OAK or OAK-D here.
Repository - https://github.com/incluit/OpenVino-Driver-Behaviour

Most of the implemented applications are ADAS applications, implementing EAR, and YAWN detection using facial landmarks. The `landmarks-regression-retail-0009` is already implemented in the Traingulation Visualisation example, so that could be used as a framework for only basic facial landmark detections. 
![image](https://user-images.githubusercontent.com/67831664/110763322-c0a9ba80-8277-11eb-9e0c-0c0fa150366f.png)
 Here's a graph displaying recorded FPS on the repo given above, reaching 22 FPS on NCS2, and could go higher to 30 on OAK-D. On the existing Gen1 Pipeline, it reaches 30FPS.

These are secondary Models deployed on `face-detection-adas` and `retail` models

**Comment by Luxonis-Brandon** [comment]
Thanks yes we should definitely add this.  Thanks for bringing it up!  And if you feel like taking a stab, please do!

**Comment by Luxonis-Brandon** [comment]
Done in https://github.com/luxonis/depthai-experiments/tree/master/gen2-face-recognition and a bonus https://github.com/luxonis/depthai-experiments/tree/master/gen2-fatigue-detection.  **Thanks to ArduCam for both!**
